chip analysis test
macarthur-lab/gnomad_lof pull request #1
Opened 2019-07-01 19:55 UTC by klaricch

2019-07-05 19:01 UTC, konradjk requested changes
Looks great! Will probably want some sort of export to a file near the end, but I presume you're on top of that.

2019-07-05 19:01 UTC, konradjk commented on constraint/chip_analysis.py
> +import hail.expr.aggregators as agg
This import isn't used, so safe to remove (it's also imported as `hl.agg` which is preferred anyway).

Also `from gnomad_hail import *` imports hail, pandas, and numpy, so can also probably remove those too.

2019-07-05 19:01 UTC, konradjk commented on constraint/chip_analysis.py
> +ht = hl.read_table(public_exomes_ht_path())
Wrap the whole script in a `def main()`

2019-07-05 19:01 UTC, konradjk commented on constraint/chip_analysis.py
> +bin_floors_age = bin_edges_age[0] # don't use -1 because want to keep upper bound as floor of n_larger
2 spaces before an inline comment

2019-07-05 19:01 UTC, konradjk commented on constraint/chip_analysis.py
> +ht20e = ht20e.annotate(variant_severity = hl.cond(ht20e.vep.transcript_consequences.consequence_terms.contains("synonymous_variant"),
You might want to use `hl.case()` to avoid the nested `cond`s and combine with the line below.

2019-07-05 19:01 UTC, konradjk commented on constraint/chip_analysis.py
> +ht20e = ht20e.annotate(age_middle = np.add(ht20e.age_hist_het[0].bin_freq, ht20e.age_hist_hom[0].bin_freq),
I think you can just use `+` here instead of `np.add` or `hl.sum` below.

2019-07-05 19:01 UTC, konradjk commented on constraint/chip_analysis.py
> +                aggregate(summed_ab_hists = hl.agg.array_agg(lambda x: hl.agg.sum(x), ht20e.ab_hist_alt.bin_freq),
you could use `hl.agg.array_sum` here if you wanted

2019-07-05 19:01 UTC, konradjk commented on constraint/chip_analysis.py
> +median_ab_hist = table_result.aggregate(hl.agg.filter(table_result.variant_severity == "synonymous", hl.agg.array_agg(lambda x: hl.median(hl.agg.collect(x)), table_result.summed_ab_hists)))
if this is proving slow, you could use `hl.agg.approx_quantiles`

2019-07-22 13:08 UTC, klaricch commented on constraint/chip_analysis.py
> +median_ab_hist = table_result.aggregate(hl.agg.filter(table_result.variant_severity == "synonymous", hl.agg.array_agg(lambda x: hl.median(hl.agg.collect(x)), table_result.summed_ab_hists)))
this step isn't slow, so will keep as is

2019-07-22 13:12 UTC, klaricch commented on constraint/chip_analysis.py
> +import hail.expr.aggregators as agg
didn't realize that, thanks! removed most of them , kept numpy to import as np

2019-08-01 14:46 UTC, konradjk approved these changes
Looks great! Just a couple of cosmetic things

2019-08-01 14:46 UTC, konradjk commented on constraint/chip_analysis.py
> +    ht = ht.annotate(chrom = ht.locus.contig)
no spaces before or after = in arguments (here and everywhere else)

2019-08-01 14:46 UTC, konradjk commented on constraint/chip_analysis.py
> +    Runs the two sample Kolmogorov-Smirnov test on the two supplied arrays, requires ndarrays with at least 2 distinct values
mood?

2019-08-01 14:46 UTC, konradjk commented on constraint/chip_analysis.py
> +            stat,p,grand_median,contigency_table = stats.median_test(a1,a2)
spaces after splitting a tuple out: `stat, p, ...`, but also, if you only ever use `p` you could either do: `_, p, _, _ = stats.median_test` or `values = stats.median_test` and then `return values[1]`. but this is fine

2019-08-06 13:40 UTC, konradjk approved these changes

2019-08-06 13:40 UTC, merged